image_upload/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include,url

urlpatterns = [
    url(r'', include('main_app.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'main_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

main_app/models.py
from django.db import models

# Create your models here.

main_app/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from PIL import Image
# Create your views here.

def index(request):
  if request.method == 'POST' and request.FILES['myfile']:
    myfile = request.FILES['myfile']
    # Testing the file if it is an image
    try:
      Image.open(myfile)
    except IOError:
      return render(request, 'main_app/index.html',{'error': 'Not a valid Image'}, status=400)
    # Initiating the filestorage to save file
    fs = FileSystemStorage()
    filename = fs.save(myfile.name, myfile)
    uploaded_file_url = fs.url(filename)
    # Redirecting the file after image upload
    return render(request, 'main_app/image.html', {'uploaded_file_url': uploaded_file_url})
  return render(request, 'main_app/index.html',{'error': ''})

main_app/templates/main_app/base.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
  <title>SynsoftGlobal</title>
</head>
<body>
  <div class="container">
    <div class="pt-3 text-center"> <img class="d-block mx-auto mb-4" src="https://www.synsoftglobal.com/wp-content/uploads/2018/01/synsoft.png" alt="" width="auto" height="auto">
    </div>

    {% block content %} {% endblock %}

    <!-- footer starts -->
    <footer class="my-5 pt-5 text-muted text-center text-small">
      <p class="mb-1">&copy; 2019 Synsoft Global</p>
    </footer>
    <!-- footer ends -->
    
    <!-- Optional JavaScript --> 
    <!-- jQuery first, then Popper.js, then Bootstrap JS --> 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" crossorigin="anonymous"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous"></script> 
    <script>
      // Add the following code if you want the name of the file appear on select
      $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
      });
    </script> 
  </div>
</body>
</html>

main_app/templates/main_app/image.html
<!-- For uploaded image -->
{% extends "main_app/base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
  <nav aria-label="breadcrumb d-flex">
    <ol class="breadcrumb d-flex justify-content-center">
      <li class="breadcrumb-item"><a href="{% url 'main_app:index' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Uploaded Image</li>
    </ol>
  </nav>
  {% if uploaded_file_url %}
	  <div class="row py-xl-4 py-md-3 py-2">
	      <div class="offset-md-2 col-md-8 order-md-1">
			    <div class="card mt-3" style="width: 18rem;margin: 0 auto;"> 
			    	{% if uploaded_file_url %}
			    		<img class="card-img-top" src="{{ uploaded_file_url }}" alt="No Image Found" />
			    	{% else %}
			    		<img class="card-img-top" src="{% static "" %}main_app/img/img_car.jpg" alt="No Image Found" />
			    	{% endif %}
			      <div class="card-body">
			        <h5 class="card-title text-center">Uploaded Image</h5>
			      </div>
			    </div>
	      </div>
	  </div>
  {% endif %}

{% endblock %}

main_app/templates/main_app/index.html
<!-- For upload form -->
{% extends "main_app/base.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
    <div class="row py-xl-5 py-md-3 py-2">
      <div class="offset-md-2 col-md-8 order-md-1 py-xl-5 py-md-3 py-2">
        <h4 class="mb-3">Upload Image</h4>
        <form class="needs-validation" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="custom-file">
            <input type="file" name="myfile" class="custom-file-input" accept="image/*">
            <label class="custom-file-label" for="customFile">Choose file</label>
          </div>
          <p style="color: red;">{{error}}</p>
          <hr class="mb-4">
          <button class="btn btn-primary btn-lg btn-block" type="submit">Upload</button>
        </form>
      </div>
    </div>
{% endblock %}